package it.rattly.objects

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Autogenerated
 */

@Serializable
data class CalendarioItem(
    @SerialName("annoCorso")
    var annoCorso: Double? = null,
    @SerialName("attivo")
    var attivo: Boolean? = null,
    @SerialName("aule")
    var aule: List<Aule?>? = null,
    @SerialName("calendari")
    var calendari: List<Calendari?>? = null,
    @SerialName("clienteId")
    var clienteId: String? = null,
    @SerialName("codiceAttivita")
    var codiceAttivita: String? = null,
    @SerialName("contestiId")
    var contestiId: List<String?>? = null,
    @SerialName("contestiMasterId")
    var contestiMasterId: List<String?>? = null,
    @SerialName("corsi")
    var corsi: List<Corsi?>? = null,
    @SerialName("dataCreazione")
    var dataCreazione: String? = null,
    @SerialName("dataFine")
    var dataFine: String? = null,
    @SerialName("dataInizio")
    var dataInizio: String? = null,
    @SerialName("dataModifica")
    var dataModifica: String? = null,
    @SerialName("docenti")
    var docenti: List<Docenti?>? = null,
    @SerialName("edifici")
    var edifici: List<Edifici?>? = null,
    @SerialName("eventoId")
    var eventoId: String? = null,
    @SerialName("icona")
    var icona: String? = null,
    @SerialName("id")
    var id: String? = null,
    @SerialName("indisponibilita")
    var indisponibilita: Boolean? = null,
    @SerialName("indisponibilitaTotale")
    var indisponibilitaTotale: Boolean? = null,
    @SerialName("indisponibilitaTotaleAule")
    var indisponibilitaTotaleAule: Boolean? = null,
    @SerialName("invioMassivoSbk")
    var invioMassivoSbk: Boolean? = null,
    @SerialName("nome")
    var nome: String? = null,
    @SerialName("nome_EN")
    var nomeEN: String? = null,
    @SerialName("orarioFine")
    var orarioFine: String? = null,
    @SerialName("orarioInizio")
    var orarioInizio: String? = null,
    @SerialName("oreAccademiche")
    var oreAccademiche: Double? = null,
    @SerialName("oreAccademicheBloccate")
    var oreAccademicheBloccate: Boolean? = null,
    @SerialName("percorsi")
    var percorsi: List<Percorsi?>? = null,
    @SerialName("risorse")
    var risorse: List<Risorse?>? = null,
    @SerialName("serieId")
    var serieId: String? = null,
    @SerialName("stato")
    var stato: String? = null,
    @SerialName("templateImpegniId")
    var templateImpegniId: String? = null,
    @SerialName("tipoAttivita")
    var tipoAttivita: TipoAttivita? = null,
    @SerialName("tipoEvento")
    var tipoEvento: TipoEvento? = null,
    @SerialName("utenteCreazioneId")
    var utenteCreazioneId: String? = null,
    @SerialName("utenteModificaId")
    var utenteModificaId: String? = null,
) {
    @Serializable
    data class Aule(
        @SerialName("abilitato")
        var abilitato: Boolean? = null,
        @SerialName("attivo")
        var attivo: Boolean? = null,
        @SerialName("capienza")
        var capienza: Double? = null,
        @SerialName("capienzaEffettiva")
        var capienzaEffettiva: Double? = null,
        @SerialName("clienteId")
        var clienteId: String? = null,
        @SerialName("codice")
        var codice: String? = null,
        @SerialName("dataCreazione")
        var dataCreazione: String? = null,
        @SerialName("dataModifica")
        var dataModifica: String? = null,
        @SerialName("descrizione")
        var descrizione: String? = null,
        @SerialName("edificio")
        var edificio: Edificio? = null,
        @SerialName("edificioId")
        var edificioId: String? = null,
        @SerialName("extCode")
        var extCode: String? = null,
        @SerialName("id")
        var id: String? = null,
        @SerialName("piano")
        var piano: Piano? = null,
        @SerialName("pianoId")
        var pianoId: String? = null,
        @SerialName("tipoAula")
        var tipoAula: TipoAula? = null,
        @SerialName("tipoAulaId")
        var tipoAulaId: String? = null,
        @SerialName("unitaOrganizzativaId")
        var unitaOrganizzativaId: String? = null,
        @SerialName("utenteCreazioneId")
        var utenteCreazioneId: String? = null,
        @SerialName("utenteModificaId")
        var utenteModificaId: String? = null,
    ) {
        @Serializable
        data class Edificio(
            @SerialName("attivo")
            var attivo: Boolean? = null,
            @SerialName("cap")
            var cap: String? = null,
            @SerialName("clienteId")
            var clienteId: String? = null,
            @SerialName("codice")
            var codice: String? = null,
            @SerialName("comune")
            var comune: String? = null,
            @SerialName("dataCreazione")
            var dataCreazione: String? = null,
            @SerialName("dataModifica")
            var dataModifica: String? = null,
            @SerialName("descrizione")
            var descrizione: String? = null,
            @SerialName("extCode")
            var extCode: String? = null,
            @SerialName("flgMigrazione")
            var flgMigrazione: Boolean? = null,
            @SerialName("utenteCreazioneId")
            var utenteCreazioneId: String? = null,
            @SerialName("utenteModificaId")
            var utenteModificaId: String? = null,
            @SerialName("via")
            var via: String? = null,
        )

        @Serializable
        data class Piano(
            @SerialName("codice")
            var codice: String? = null,
            @SerialName("descrizione")
            var descrizione: String? = null,
        )

        @Serializable
        data class TipoAula(
            @SerialName("codice")
            var codice: String? = null,
            @SerialName("descrizione")
            var descrizione: String? = null,
        )
    }

    @Serializable
    data class Calendari(
        @SerialName("annoAccademicoId")
        var annoAccademicoId: String? = null,
        @SerialName("attivo")
        var attivo: Boolean? = null,
        @SerialName("bloccato")
        var bloccato: Boolean? = null,
        @SerialName("clienteId")
        var clienteId: String? = null,
        @SerialName("codice")
        var codice: String? = null,
        @SerialName("corsoId")
        var corsoId: String? = null,
        @SerialName("dataCreazione")
        var dataCreazione: String? = null,
        @SerialName("dataFine")
        var dataFine: String? = null,
        @SerialName("dataInizio")
        var dataInizio: String? = null,
        @SerialName("dataModifica")
        var dataModifica: String? = null,
        @SerialName("descrizione")
        var descrizione: String? = null,
        @SerialName("extCode")
        var extCode: String? = null,
        @SerialName("id")
        var id: String? = null,
        @SerialName("tipoCalendario")
        var tipoCalendario: String? = null,
        @SerialName("utenteCreazioneId")
        var utenteCreazioneId: String? = null,
        @SerialName("utenteModificaId")
        var utenteModificaId: String? = null,
    )

    @Serializable
    data class Corsi(
        @SerialName("abilitato")
        var abilitato: Boolean? = null,
        @SerialName("anteRiforma")
        var anteRiforma: Boolean? = null,
        @SerialName("attivo")
        var attivo: Boolean? = null,
        @SerialName("bloccato")
        var bloccato: Boolean? = null,
        @SerialName("clienteId")
        var clienteId: String? = null,
        @SerialName("codice")
        var codice: String? = null,
        @SerialName("dataCreazione")
        var dataCreazione: String? = null,
        @SerialName("dataModifica")
        var dataModifica: String? = null,
        @SerialName("descrizione")
        var descrizione: String? = null,
        @SerialName("descrizione_EN")
        var descrizioneEN: String? = null,
        @SerialName("extCode")
        var extCode: String? = null,
        @SerialName("id")
        var id: String? = null,
        @SerialName("tipoCorso")
        var tipoCorso: TipoCorso? = null,
        @SerialName("tipoCorsoId")
        var tipoCorsoId: String? = null,
        @SerialName("unitaOrganizzativaId")
        var unitaOrganizzativaId: String? = null,
        @SerialName("utenteCreazioneId")
        var utenteCreazioneId: String? = null,
        @SerialName("utenteModificaId")
        var utenteModificaId: String? = null,
    ) {
        @Serializable
        data class TipoCorso(
            @SerialName("attivo")
            var attivo: Boolean? = null,
            @SerialName("bloccato")
            var bloccato: Boolean? = null,
            @SerialName("clienteId")
            var clienteId: String? = null,
            @SerialName("codice")
            var codice: String? = null,
            @SerialName("dataCreazione")
            var dataCreazione: String? = null,
            @SerialName("dataModifica")
            var dataModifica: String? = null,
            @SerialName("descrizione")
            var descrizione: String? = null,
            @SerialName("descrizione_EN")
            var descrizioneEN: String? = null,
            @SerialName("extCode")
            var extCode: String? = null,
            @SerialName("_id")
            var id: String? = null,
            @SerialName("utenteCreazioneId")
            var utenteCreazioneId: String? = null,
            @SerialName("utenteModificaId")
            var utenteModificaId: String? = null,
        )
    }

    @Serializable
    data class Docenti(
        @SerialName("cognome")
        var cognome: String? = null,
        @SerialName("id")
        var id: String? = null,
        @SerialName("nome")
        var nome: String? = null,
    )

    @Serializable
    data class Edifici(
        @SerialName("attivo")
        var attivo: Boolean? = null,
        @SerialName("cap")
        var cap: String? = null,
        @SerialName("clienteId")
        var clienteId: String? = null,
        @SerialName("codice")
        var codice: String? = null,
        @SerialName("comune")
        var comune: String? = null,
        @SerialName("dataCreazione")
        var dataCreazione: String? = null,
        @SerialName("dataModifica")
        var dataModifica: String? = null,
        @SerialName("descrizione")
        var descrizione: String? = null,
        @SerialName("extCode")
        var extCode: String? = null,
        @SerialName("flgMigrazione")
        var flgMigrazione: Boolean? = null,
        @SerialName("provincia")
        var provincia: String? = null,
        @SerialName("utenteCreazioneId")
        var utenteCreazioneId: String? = null,
        @SerialName("utenteModificaId")
        var utenteModificaId: String? = null,
        @SerialName("via")
        var via: String? = null,
    )

    @Serializable
    data class Percorsi(
        @SerialName("annoOrdinamento")
        var annoOrdinamento: Double? = null,
        @SerialName("annoRegolamento")
        var annoRegolamento: Double? = null,
        @SerialName("attivo")
        var attivo: Boolean? = null,
        @SerialName("bloccato")
        var bloccato: Boolean? = null,
        @SerialName("clienteId")
        var clienteId: String? = null,
        @SerialName("codice")
        var codice: String? = null,
        @SerialName("corsoId")
        var corsoId: String? = null,
        @SerialName("dataCreazione")
        var dataCreazione: String? = null,
        @SerialName("dataModifica")
        var dataModifica: String? = null,
        @SerialName("descrizione")
        var descrizione: String? = null,
        @SerialName("extCode")
        var extCode: String? = null,
        @SerialName("id")
        var id: String? = null,
        @SerialName("note")
        var note: String? = null,
        @SerialName("utenteCreazioneId")
        var utenteCreazioneId: String? = null,
        @SerialName("utenteModificaId")
        var utenteModificaId: String? = null,
    )

    @Serializable
    data class Risorse(
        @SerialName("aula")
        var aula: Aula? = null,
        @SerialName("aulaId")
        var aulaId: String? = null,
        @SerialName("dataLookup")
        var dataLookup: String? = null,
        @SerialName("docente")
        var docente: Docente? = null,
        @SerialName("docenteId")
        var docenteId: String? = null,
        @SerialName("risorsaId")
        var risorsaId: String? = null,
    ) {
        @Serializable
        data class Aula(
            @SerialName("abilitato")
            var abilitato: Boolean? = null,
            @SerialName("attivo")
            var attivo: Boolean? = null,
            @SerialName("capienza")
            var capienza: Double? = null,
            @SerialName("capienzaEffettiva")
            var capienzaEffettiva: Double? = null,
            @SerialName("clienteId")
            var clienteId: String? = null,
            @SerialName("codice")
            var codice: String? = null,
            @SerialName("dataCreazione")
            var dataCreazione: String? = null,
            @SerialName("dataModifica")
            var dataModifica: String? = null,
            @SerialName("descrizione")
            var descrizione: String? = null,
            @SerialName("edificio")
            var edificio: Edificio? = null,
            @SerialName("edificioId")
            var edificioId: String? = null,
            @SerialName("extCode")
            var extCode: String? = null,
            @SerialName("id")
            var id: String? = null,
            @SerialName("piano")
            var piano: Piano? = null,
            @SerialName("pianoId")
            var pianoId: String? = null,
            @SerialName("tipoAulaId")
            var tipoAulaId: String? = null,
            @SerialName("unitaOrganizzativaId")
            var unitaOrganizzativaId: String? = null,
            @SerialName("utenteCreazioneId")
            var utenteCreazioneId: String? = null,
            @SerialName("utenteModificaId")
            var utenteModificaId: String? = null,
        ) {
            @Serializable
            data class Edificio(
                @SerialName("attivo")
                var attivo: Boolean? = null,
                @SerialName("cap")
                var cap: String? = null,
                @SerialName("clienteId")
                var clienteId: String? = null,
                @SerialName("codice")
                var codice: String? = null,
                @SerialName("comune")
                var comune: String? = null,
                @SerialName("dataCreazione")
                var dataCreazione: String? = null,
                @SerialName("dataModifica")
                var dataModifica: String? = null,
                @SerialName("descrizione")
                var descrizione: String? = null,
                @SerialName("extCode")
                var extCode: String? = null,
                @SerialName("flgMigrazione")
                var flgMigrazione: Boolean? = null,
                @SerialName("utenteCreazioneId")
                var utenteCreazioneId: String? = null,
                @SerialName("utenteModificaId")
                var utenteModificaId: String? = null,
                @SerialName("via")
                var via: String? = null,
            )

            @Serializable
            data class Piano(
                @SerialName("codice")
                var codice: String? = null,
                @SerialName("descrizione")
                var descrizione: String? = null,
            )
        }

        @Serializable
        data class Docente(
            @SerialName("cognome")
            var cognome: String? = null,
            @SerialName("id")
            var id: String? = null,
            @SerialName("nome")
            var nome: String? = null,
        )
    }

    @Serializable
    data class TipoAttivita(
        @SerialName("abilitato")
        var abilitato: Boolean? = null,
        @SerialName("codice")
        var codice: String? = null,
        @SerialName("defaultDurataImpegni")
        var defaultDurataImpegni: Double? = null,
        @SerialName("descrizione")
        var descrizione: String? = null,
    )

    @Serializable
    data class TipoEvento(
        @SerialName("attivitaDidattica")
        var attivitaDidattica: Boolean? = null,
        @SerialName("attivo")
        var attivo: Boolean? = null,
        @SerialName("bloccato")
        var bloccato: Boolean? = null,
        @SerialName("clienteId")
        var clienteId: String? = null,
        @SerialName("codice")
        var codice: String? = null,
        @SerialName("colonneDettagliDidattici")
        var colonneDettagliDidattici: ColonneDettagliDidattici? = null,
        @SerialName("dataCreazione")
        var dataCreazione: String? = null,
        @SerialName("dataModifica")
        var dataModifica: String? = null,
        @SerialName("descrizione")
        var descrizione: String? = null,
        @SerialName("extCode")
        var extCode: String? = null,
        @SerialName("icona")
        var icona: String? = null,
        @SerialName("_id")
        var id: String? = null,
        @SerialName("tipiAttivita")
        var tipiAttivita: List<TipiAttivita?>? = null,
        @SerialName("utenteCreazioneId")
        var utenteCreazioneId: String? = null,
        @SerialName("utenteModificaId")
        var utenteModificaId: String? = null,
        @SerialName("visibileCreatoreImpegniPersonali")
        var visibileCreatoreImpegniPersonali: Boolean? = null,
    ) {
        @Serializable
        data class ColonneDettagliDidattici(
            @SerialName("annoCorso")
            var annoCorso: Boolean? = null,
            @SerialName("codiceAF")
            var codiceAF: Boolean? = null,
            @SerialName("corsoDiStudio")
            var corsoDiStudio: Boolean? = null,
            @SerialName("nome")
            var nome: Boolean? = null,
            @SerialName("partizione")
            var partizione: Boolean? = null,
        )

        @Serializable
        data class TipiAttivita(
            @SerialName("abilitato")
            var abilitato: Boolean? = null,
            @SerialName("codice")
            var codice: String? = null,
            @SerialName("defaultDurataImpegni")
            var defaultDurataImpegni: Double? = null,
            @SerialName("descrizione")
            var descrizione: String? = null,
        )
    }
}