package it.rattly.objects


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Autogenerated
 */

@Serializable
data class CorsiItem(
    @SerialName("id")
    var id: String? = null,
    @SerialName("payload")
    var payload: Payload? = null
) {
    @Serializable
    data class Payload(
        @SerialName("annoAccademico")
        var annoAccademico: String? = null,
        @SerialName("calendario")
        var calendario: List<String?>? = null,
        @SerialName("coloraPer")
        var coloraPer: String? = null,
        @SerialName("contesto")
        var contesto: Contesto? = null,
        @SerialName("corsi")
        var corsi: List<String?>? = null,
        @SerialName("anniCorso")
        var anniCorso: List<String?>? = null,
        @SerialName("dataFine")
        var dataFine: String? = null,
        @SerialName("dataInizio")
        var dataInizio: String? = null,
        @SerialName("giorniNonVisualizzati")
        var giorniNonVisualizzati: List<Int?>? = null,
        @SerialName("inizioAnnoAccademico")
        var inizioAnnoAccademico: String? = null,
        @SerialName("mostraIconeStatoImpegni")
        var mostraIconeStatoImpegni: Boolean? = null,
        @SerialName("mostraPrimoDettaglio")
        var mostraPrimoDettaglio: Boolean? = null,
        @SerialName("mostraSempreAuleTeledidattica")
        var mostraSempreAuleTeledidattica: Boolean? = null,
        @SerialName("percorsi")
        var percorsi: List<String?>? = null,
        @SerialName("ricercaLike")
        var ricercaLike: Boolean? = null,
        @SerialName("statoImpegni")
        var statoImpegni: List<String?>? = null,
        @SerialName("switchRealeTemplate")
        var switchRealeTemplate: Boolean? = null,
        @SerialName("template")
        var template: Boolean? = null,
        @SerialName("tipiEvento")
        var tipiEvento: List<String?>? = null,
        @SerialName("tipoAttivita")
        var tipoAttivita: List<String?>? = null,
        @SerialName("tipoLink")
        var tipoLink: String? = null,
        @SerialName("titolo")
        var titolo: String? = null,
    ) {
        @Serializable
        data class Contesto(
            @SerialName("codice")
            var codice: String? = null,
            @SerialName("id")
            var id: String? = null
        )
    }
}